### ISSUE TITLE
search is broken

### ISSUE THREAD

**Issue by fommil** [vincekd/Chrome_Emacs_Keys#10]
When I use `C-s` I get a search popup at the bottom which doesn't appear to work:
1. every time I type a character, the windows scrolls down a line
2. every time I type a character, the selected search hit seems to move along one
3. repeated `C-s` cancel the search results instead of incrementing like I would expect in emacs.

To be honest, I'd really just rather have a solution that finds the closest match for the emacs command instead of trying to reproduce functionality. `C-s` should just open the standard chromium find box like a stock `C-f` would.

**Comment by vincekd** [comment]
Yeah, the search functionality was never completed. I made this three years ago, and haven't really used it since then. You might want to try a different extension: https://github.com/clvrobj/Emacsome

**Comment by vincekd** [comment]
https://github.com/vincekd/Chrome_Emacs_Keys/issues/4
