### ISSUE TITLE
yanking not working

### ISSUE THREAD

**Issue by fommil** [vincekd/Chrome_Emacs_Keys#9]
If I `M-w` some text and then `C-y`, nothing is yanked.

Also, if I have something in my clipboard, e.g. from an external application such as emacs, the `C-y` isn't working either.

Is this supposed to work?

**Comment by vincekd** [comment]
No, for a while chrome did not support copy/paste but it now appears to.
Shouldn't be hard to add if you want to submit some code.

**Comment by fommil** [comment]
I would if I knew javascript at all. Not one of my best languages ;-)
